# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 02:41
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moderna_theme', '0023_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('_order',)},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='site',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
